import type { Tool } from '@/types'

/**
 * Static tool definitions — mirrors the backend TOOLS registry.
 * Used as an instant fallback so the Tools page renders even when the
 * backend is unreachable (demo mode / env not configured).
 */
export const STATIC_TOOLS: Tool[] = [
  {
    tool_name: 'email-breach-check',
    category: 'email',
    description: 'Check if an email address has appeared in known data breaches.',
    risk_level: 'medium',
    input_schema: [{ name: 'email', type: 'email', required: true, description: 'Email address to check' }],
    requires_api_key: true,
  },
  {
    tool_name: 'email-verify',
    category: 'email',
    description: 'Verify email deliverability via MX record and SMTP check.',
    risk_level: 'low',
    input_schema: [{ name: 'email', type: 'email', required: true, description: 'Email address to verify' }],
    requires_api_key: false,
  },
  {
    tool_name: 'email-headers',
    category: 'email',
    description: 'Parse and analyze email headers to trace origin and routing.',
    risk_level: 'low',
    input_schema: [{ name: 'headers', type: 'textarea', required: true, description: 'Raw email header text' }],
    requires_api_key: false,
  },
  {
    tool_name: 'dns-lookup',
    category: 'domain',
    description: 'Perform DNS lookups for A, AAAA, MX, NS, TXT, and CNAME records.',
    risk_level: 'low',
    input_schema: [{ name: 'domain', type: 'text', required: true, description: 'Domain name to query' }],
    requires_api_key: false,
  },
  {
    tool_name: 'whois',
    category: 'domain',
    description: 'Retrieve WHOIS registration data for a domain.',
    risk_level: 'low',
    input_schema: [{ name: 'domain', type: 'text', required: true, description: 'Domain to query WHOIS for' }],
    requires_api_key: false,
  },
  {
    tool_name: 'ssl-cert',
    category: 'domain',
    description: 'Inspect the SSL/TLS certificate of a host for validity and details.',
    risk_level: 'low',
    input_schema: [{ name: 'host', type: 'text', required: true, description: 'Hostname or domain' }],
    requires_api_key: false,
  },
  {
    tool_name: 'subdomain-enum',
    category: 'domain',
    description: 'Enumerate subdomains using passive DNS and certificate transparency logs.',
    risk_level: 'medium',
    input_schema: [{ name: 'domain', type: 'text', required: true, description: 'Root domain to enumerate' }],
    requires_api_key: false,
  },
  {
    tool_name: 'ip-geolocate',
    category: 'ip',
    description: 'Get geolocation data (country, city, coordinates, ASN) for an IP address.',
    risk_level: 'low',
    input_schema: [{ name: 'ip', type: 'text', required: true, description: 'IPv4 or IPv6 address' }],
    requires_api_key: false,
  },
  {
    tool_name: 'ip-reputation',
    category: 'ip',
    description: 'Check an IP address against threat intelligence and abuse databases.',
    risk_level: 'medium',
    input_schema: [{ name: 'ip', type: 'text', required: true, description: 'IPv4 or IPv6 address' }],
    requires_api_key: true,
  },
  {
    tool_name: 'port-scan',
    category: 'ip',
    description: 'Scan common ports on a host to identify open services.',
    risk_level: 'high',
    input_schema: [{ name: 'host', type: 'text', required: true, description: 'Hostname or IP address' }],
    requires_api_key: false,
  },
  {
    tool_name: 'username-check',
    category: 'username',
    description: 'Check username availability across major social networks and platforms.',
    risk_level: 'low',
    input_schema: [{ name: 'username', type: 'text', required: true, description: 'Username to search for' }],
    requires_api_key: false,
  },
  {
    tool_name: 'phone-lookup',
    category: 'phone',
    description: 'Look up carrier, region, and line type for a phone number.',
    risk_level: 'medium',
    input_schema: [{ name: 'phone', type: 'text', required: true, description: 'Phone number in E.164 format' }],
    requires_api_key: true,
  },
  {
    tool_name: 'phone-format',
    category: 'phone',
    description: 'Parse and format a phone number into international and national formats.',
    risk_level: 'low',
    input_schema: [{ name: 'phone', type: 'text', required: true, description: 'Raw phone number string' }],
    requires_api_key: false,
  },
  {
    tool_name: 'metadata-extract',
    category: 'metadata',
    description: 'Extract EXIF and document metadata from uploaded files or URLs.',
    risk_level: 'low',
    input_schema: [{ name: 'url', type: 'text', required: false, description: 'Publicly accessible URL to the file' }],
    requires_api_key: false,
  },
  {
    tool_name: 'github-osint',
    category: 'social',
    description: 'Gather OSINT data from a GitHub user profile: repos, stars, orgs, email leaks.',
    risk_level: 'low',
    input_schema: [{ name: 'username', type: 'text', required: true, description: 'GitHub username' }],
    requires_api_key: false,
  },
  {
    tool_name: 'password-strength',
    category: 'security',
    description: 'Analyse password strength, entropy, and pattern weaknesses.',
    risk_level: 'low',
    input_schema: [{ name: 'password', type: 'text', required: true, description: 'Password to evaluate' }],
    requires_api_key: false,
  },
]
